-- Starter outreach email templates (PT-PT) for each active industry × use case.
-- Generated by scripts/seed-outreach-templates.mjs — edit there and regenerate.
-- Idempotent: inserts a template only if its name is not already present.
-- Drafts only: nothing sends until a campaign is built, given recipients, and
-- activated. Merge fields: {{firstName}}, {{business}}.

insert into outreach_templates (name, subject, body_html, body_text)
select 'Restaurantes · 1. Apresentação (sem comissões)', 'Reservas para o {{business}} sem comissões', '<p>Olá {{firstName}},</p>
<p>Reparei que o {{business}} recebe reservas — provavelmente por telefone, Instagram ou através de plataformas como o TheFork.</p>
<p>A Guest Overflow dá ao {{business}} a sua própria página de reservas, com a sua marca: os clientes reservam online, sem comissão por reserva e sem intermediários. Os contactos e as preferências ficam seus, não da plataforma.</p>
<p>Preço fixo mensal, e tratamos nós da configuração e da migração — não precisa de fazer nada.</p>
<p>Faria sentido mostrar-lhe numa demonstração de 20 minutos, sem compromisso?</p>
<p>Com os melhores cumprimentos,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Reparei que o {{business}} recebe reservas — provavelmente por telefone, Instagram ou através de plataformas como o TheFork.

A Guest Overflow dá ao {{business}} a sua própria página de reservas, com a sua marca: os clientes reservam online, sem comissão por reserva e sem intermediários. Os contactos e as preferências ficam seus, não da plataforma.

Preço fixo mensal, e tratamos nós da configuração e da migração — não precisa de fazer nada.

Faria sentido mostrar-lhe numa demonstração de 20 minutos, sem compromisso?

Com os melhores cumprimentos,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Restaurantes · 1. Apresentação (sem comissões)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Restaurantes · 2. Seguimento (faltas / no-shows)', 'Re: Reservas para o {{business}}', '<p>Olá {{firstName}},</p>
<p>Fica só o seguimento da minha mensagem.</p>
<p>Um ponto que costuma pesar nos restaurantes são as faltas — sobretudo as mesas grandes ao fim de semana. Com a Guest Overflow pode pedir um pequeno sinal na reserva (MB WAY, Multibanco ou cartão, na sua própria conta Stripe), o que reduz bastante os no-shows — e sem comissões à mistura.</p>
<p>Bastam 20 minutos para lhe mostrar como ficaria para o {{business}}. Quando lhe dá jeito esta semana?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Fica só o seguimento da minha mensagem.

Um ponto que costuma pesar nos restaurantes são as faltas — sobretudo as mesas grandes ao fim de semana. Com a Guest Overflow pode pedir um pequeno sinal na reserva (MB WAY, Multibanco ou cartão, na sua própria conta Stripe), o que reduz bastante os no-shows — e sem comissões à mistura.

Bastam 20 minutos para lhe mostrar como ficaria para o {{business}}. Quando lhe dá jeito esta semana?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Restaurantes · 2. Seguimento (faltas / no-shows)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Restaurantes · 3. Prova (parceiro fundador)', 'Deixo o {{business}} a funcionar — sem trabalho seu', '<p>Olá {{firstName}},</p>
<p>Uma palavra sobre quem somos: passámos anos a construir sites de alta conversão para negócios locais, e quase todas as conversas terminavam na mesma pergunta — "a reserva pode ficar com a minha marca?". O Guest Overflow é essa resposta.</p>
<p>Estamos a começar de propósito com um grupo pequeno de parceiros fundadores, para acompanhar cada restaurante de perto — com três meses a metade do preço.</p>
<p>Da sua parte é simples: tratamos da configuração e da migração. Posso mostrar-lhe o resultado para o {{business}} numa demonstração de 20 minutos?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Uma palavra sobre quem somos: passámos anos a construir sites de alta conversão para negócios locais, e quase todas as conversas terminavam na mesma pergunta — "a reserva pode ficar com a minha marca?". O Guest Overflow é essa resposta.

Estamos a começar de propósito com um grupo pequeno de parceiros fundadores, para acompanhar cada restaurante de perto — com três meses a metade do preço.

Da sua parte é simples: tratamos da configuração e da migração. Posso mostrar-lhe o resultado para o {{business}} numa demonstração de 20 minutos?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Restaurantes · 3. Prova (parceiro fundador)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Restaurantes · 4. Último contacto', 'Fecho o assunto, {{firstName}}?', '<p>Olá {{firstName}},</p>
<p>Não quero estar a insistir. Se ter as reservas com a marca do {{business}} e sem comissões não for prioridade agora, não há problema nenhum e fico por aqui.</p>
<p>Se preferir, deixo o convite em aberto para ver uma demonstração quando quiser — sem compromisso.</p>
<p>Obrigado pelo tempo,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Não quero estar a insistir. Se ter as reservas com a marca do {{business}} e sem comissões não for prioridade agora, não há problema nenhum e fico por aqui.

Se preferir, deixo o convite em aberto para ver uma demonstração quando quiser — sem compromisso.

Obrigado pelo tempo,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Restaurantes · 4. Último contacto');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Restaurantes · 5. Migração do Quandoo (gratuita)', 'O Quandoo vai fechar — e as reservas do {{business}}?', '<p>Olá {{firstName}},</p>
<p>Se o {{business}} recebe reservas pelo Quandoo, vale a pena saber: o Quandoo está a encerrar e deixa de aceitar novas reservas já em setembro de 2026.</p>
<p>Antes do prazo, podemos migrar gratuitamente a sua lista de clientes e o histórico de reservas para uma página de reservas que é sua — com a sua marca, sem comissão, nunca. Fica com todos os contactos; não perde ninguém.</p>
<p>Quer que tratemos da migração do {{business}}? Bastam 20 minutos para começar.</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Se o {{business}} recebe reservas pelo Quandoo, vale a pena saber: o Quandoo está a encerrar e deixa de aceitar novas reservas já em setembro de 2026.

Antes do prazo, podemos migrar gratuitamente a sua lista de clientes e o histórico de reservas para uma página de reservas que é sua — com a sua marca, sem comissão, nunca. Fica com todos os contactos; não perde ninguém.

Quer que tratemos da migração do {{business}}? Bastam 20 minutos para começar.

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Restaurantes · 5. Migração do Quandoo (gratuita)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Hotéis · 1. Apresentação (reservas diretas)', 'Reservas diretas para o {{business}}, sem comissões', '<p>Olá {{firstName}},</p>
<p>A maior parte das reservas de hotéis e hostels como o {{business}} acaba por passar pela Booking.com ou Expedia — e com elas 15% a 18% de comissão em cada estadia.</p>
<p>A Guest Overflow dá ao {{business}} uma página de reservas diretas, com a sua marca: o hóspede reserva no seu próprio site, sem comissão por reserva, e os dados do hóspede ficam seus.</p>
<p>Preço fixo mensal e a configuração tratada por nós.</p>
<p>Mostro-lhe numa demonstração de 20 minutos, sem compromisso?</p>
<p>Com os melhores cumprimentos,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

A maior parte das reservas de hotéis e hostels como o {{business}} acaba por passar pela Booking.com ou Expedia — e com elas 15% a 18% de comissão em cada estadia.

A Guest Overflow dá ao {{business}} uma página de reservas diretas, com a sua marca: o hóspede reserva no seu próprio site, sem comissão por reserva, e os dados do hóspede ficam seus.

Preço fixo mensal e a configuração tratada por nós.

Mostro-lhe numa demonstração de 20 minutos, sem compromisso?

Com os melhores cumprimentos,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Hotéis · 1. Apresentação (reservas diretas)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Hotéis · 2. Seguimento (comissões Booking/Expedia)', 'Re: Reservas diretas para o {{business}}', '<p>Olá {{firstName}},</p>
<p>Só a recuperar a minha mensagem anterior.</p>
<p>Uma conta rápida: por cada 10.000€ de reservas que passam pela Booking, cerca de 1.500€ a 1.800€ ficam em comissões. As reservas diretas no site do {{business}} eliminam essa fatia — e o cliente passa a ser seu, não da plataforma. Em Portugal, por lei, pode até definir a sua tarifa direta abaixo da da OTA.</p>
<p>São 20 minutos para lhe mostrar como ficaria. Tem disponibilidade esta semana?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Só a recuperar a minha mensagem anterior.

Uma conta rápida: por cada 10.000€ de reservas que passam pela Booking, cerca de 1.500€ a 1.800€ ficam em comissões. As reservas diretas no site do {{business}} eliminam essa fatia — e o cliente passa a ser seu, não da plataforma. Em Portugal, por lei, pode até definir a sua tarifa direta abaixo da da OTA.

São 20 minutos para lhe mostrar como ficaria. Tem disponibilidade esta semana?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Hotéis · 2. Seguimento (comissões Booking/Expedia)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Hotéis · 3. Prova (parceiro fundador)', 'Página de reservas do {{business}} pronta sem trabalho seu', '<p>Olá {{firstName}},</p>
<p>Uma nota sobre quem somos: viemos de anos a construir sites de alta conversão para negócios locais, e o Guest Overflow é o que esses clientes nos pediam — reservas com a sua própria marca.</p>
<p>Estamos a começar com um grupo pequeno de parceiros fundadores, acompanhados de perto e com três meses a metade do preço. A parte difícil é nossa: montamos a página do {{business}}, ligamos os pagamentos e deixamos as reservas diretas a funcionar em poucos dias.</p>
<p>Posso mostrar-lhe o resultado numa demonstração de 20 minutos?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Uma nota sobre quem somos: viemos de anos a construir sites de alta conversão para negócios locais, e o Guest Overflow é o que esses clientes nos pediam — reservas com a sua própria marca.

Estamos a começar com um grupo pequeno de parceiros fundadores, acompanhados de perto e com três meses a metade do preço. A parte difícil é nossa: montamos a página do {{business}}, ligamos os pagamentos e deixamos as reservas diretas a funcionar em poucos dias.

Posso mostrar-lhe o resultado numa demonstração de 20 minutos?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Hotéis · 3. Prova (parceiro fundador)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Hotéis · 4. Último contacto', 'Fecho o assunto, {{firstName}}?', '<p>Olá {{firstName}},</p>
<p>Última mensagem da minha parte. Se reduzir as comissões da Booking e ter reservas diretas com a marca do {{business}} não for prioridade agora, sem problema nenhum.</p>
<p>Fica o convite em aberto para uma demonstração quando fizer sentido.</p>
<p>Obrigado pelo tempo,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Última mensagem da minha parte. Se reduzir as comissões da Booking e ter reservas diretas com a marca do {{business}} não for prioridade agora, sem problema nenhum.

Fica o convite em aberto para uma demonstração quando fizer sentido.

Obrigado pelo tempo,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Hotéis · 4. Último contacto');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Salões & Barbearias · 1. Apresentação (sem comissões)', 'Marcações online para o {{business}}, sem comissões', '<p>Olá {{firstName}},</p>
<p>Muitos salões e barbearias como o {{business}} ainda recebem marcações por telefone ou por DM no Instagram — dá trabalho e perdem-se marcações.</p>
<p>A Guest Overflow dá ao {{business}} uma página de marcações com a sua marca: os clientes marcam online a qualquer hora, sem comissão por marcação e sem os extras pagos de plataformas como a Fresha ou a Booksy.</p>
<p>Preço fixo e a configuração tratada por nós.</p>
<p>Mostro-lhe numa demonstração de 20 minutos, sem compromisso?</p>
<p>Com os melhores cumprimentos,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Muitos salões e barbearias como o {{business}} ainda recebem marcações por telefone ou por DM no Instagram — dá trabalho e perdem-se marcações.

A Guest Overflow dá ao {{business}} uma página de marcações com a sua marca: os clientes marcam online a qualquer hora, sem comissão por marcação e sem os extras pagos de plataformas como a Fresha ou a Booksy.

Preço fixo e a configuração tratada por nós.

Mostro-lhe numa demonstração de 20 minutos, sem compromisso?

Com os melhores cumprimentos,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Salões & Barbearias · 1. Apresentação (sem comissões)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Salões & Barbearias · 2. Seguimento (faltas / no-shows)', 'Re: Marcações online para o {{business}}', '<p>Olá {{firstName}},</p>
<p>Só a dar seguimento à minha mensagem.</p>
<p>As faltas deixam a cadeira vazia em horários de pico — tempo que não se vende duas vezes. Com a Guest Overflow pode pedir um sinal na marcação (MB WAY, Multibanco ou cartão, na sua conta Stripe) — menos faltas, e sem comissões à mistura.</p>
<p>São 20 minutos para lhe mostrar como ficaria para o {{business}}. Quando lhe dá jeito?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Só a dar seguimento à minha mensagem.

As faltas deixam a cadeira vazia em horários de pico — tempo que não se vende duas vezes. Com a Guest Overflow pode pedir um sinal na marcação (MB WAY, Multibanco ou cartão, na sua conta Stripe) — menos faltas, e sem comissões à mistura.

São 20 minutos para lhe mostrar como ficaria para o {{business}}. Quando lhe dá jeito?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Salões & Barbearias · 2. Seguimento (faltas / no-shows)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Salões & Barbearias · 3. Prova (parceiro fundador)', 'Deixo o {{business}} a receber marcações online sem trabalho seu', '<p>Olá {{firstName}},</p>
<p>Sobre quem somos: passámos anos a fazer sites de alta conversão para negócios locais, e o Guest Overflow nasceu do que esses clientes pediam — marcações com a sua marca, sem comissões.</p>
<p>Estamos a começar com um grupo pequeno de parceiros fundadores, com três meses a metade do preço e acompanhamento próximo. Do seu lado é simples: montamos a página do {{business}}, com os seus serviços e horários, e deixamos as marcações a funcionar.</p>
<p>Posso mostrar-lhe o resultado numa demonstração de 20 minutos?</p>
<p>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Sobre quem somos: passámos anos a fazer sites de alta conversão para negócios locais, e o Guest Overflow nasceu do que esses clientes pediam — marcações com a sua marca, sem comissões.

Estamos a começar com um grupo pequeno de parceiros fundadores, com três meses a metade do preço e acompanhamento próximo. Do seu lado é simples: montamos a página do {{business}}, com os seus serviços e horários, e deixamos as marcações a funcionar.

Posso mostrar-lhe o resultado numa demonstração de 20 minutos?

[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Salões & Barbearias · 3. Prova (parceiro fundador)');

insert into outreach_templates (name, subject, body_html, body_text)
select 'Salões & Barbearias · 4. Último contacto', 'Fecho o assunto, {{firstName}}?', '<p>Olá {{firstName}},</p>
<p>Não quero insistir. Se ter marcações online com a marca do {{business}} e sem comissões não for prioridade agora, sem problema.</p>
<p>Deixo o convite para uma demonstração quando quiser, sem compromisso.</p>
<p>Obrigado,<br/>[O seu nome] · Guest Overflow</p>', 'Olá {{firstName}},

Não quero insistir. Se ter marcações online com a marca do {{business}} e sem comissões não for prioridade agora, sem problema.

Deixo o convite para uma demonstração quando quiser, sem compromisso.

Obrigado,
[O seu nome] · Guest Overflow'
where not exists (select 1 from outreach_templates where name = 'Salões & Barbearias · 4. Último contacto');
